### ISSUE TITLE
Conflict with Pipewire and Pulseaudio

### ISSUE THREAD

**Issue by CinPoU** [HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5#11]
Hi,

I’ve installed HASS supervised on a Raspbian bookworm with GUI on a raspberry pi 5.
By default, it uses Pipewire, but HASS uses a container Pulseaudio.
I’ve to disable HASS-audio container to keep the sound  running on my Shairport server.
Is it a way to force HASS talking on the system Pipewire?

Best regards

**Comment by HuckleberryLovesYou** [comment]
Hey,
thanks for opening a issue.
I don't use any audio in combination with Homeassistant Supervised, but I think you should take a look at issue #4 as it is also referring to a audio problem.
Maybe it can help you with your problem.

Please let me know, if it was the solution to your problem.

**Comment by CinPoU** [comment]
Thank you for your answer.
It don't solve the problem, so i will try a minimal installation, without pipewire, and launch the interface via a firefox kiosk.

**Comment by HuckleberryLovesYou** [comment]
Hey CinPoU,
it's been quite a while since opening this issue here.

There has been another issue #21 referencing audio problems.
Maybe you're still facing the same problem.
I added a fix in #22 for this issue [in the Readme.md](https://github.com/HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5?tab=readme-ov-file#no-audio-on-host-after-homeassisant-supervised-installation).

Let me know if this fixes your issue too.

Looking forward to hearing from you,
Tim

**Comment by CinPoU** [comment]
Hey,
As I said before, I install a minimal instalation and use firefox with kiosk mode. Now I don't have problem anymore. Hass and firefox can play sounds.
I'm not totally satisfied while using assist. The raspberry is very slow to process the stt. I will probabky install Hass on a nuc later, and the raspberry will turn as a satellite. Will see if it s always a problem in this case.
Best regards
