### ISSUE TITLE
Possible  Error in "kernel setup", minor

### ISSUE THREAD

**Issue by skutoroff** [HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5#19]
**Describe the bug**
I've run this several times in getting to final success with Hubitat.
The script in "kernel setup" which modifies /boot/firmware/cmdline.txt, I think the script is adding the new commands following a newline. I may be wrong.
I think this file requires all entries on one line, hence cmdline.
When I examined the file, I removed the newline. Only reason I suspect this is when I had to modify this file to fix a VNC screen resolution error, the instructions were very specific about this.  I followed these instructions and my VNC screen issue was fixed.

**To Reproduce**
Run the script and examine the cmdline.txt file in an editor.

**Expected behavior**
I expect the final file to be one long line (as I was told it needs to be)
Test that the change works.

**Screenshots**
NA

**Server information:**
 - OS: Raspberry Pi Bookworm 12, 64 Bit for Raspberry Pi 4 (or 5)
 - OS-Agent Version: 

My configuration.yaml file:
My Homeassistant Core log file:
My Homeassistant Supervisor log file:
My Homeassistant Host log file:

**Comment by HuckleberryLovesYou** [comment]
Hey Steven
thanks for reporting the bug!
You're right. If cmdline.txt has a new line character in the file, it may lead to unwanted behavior.

The Bug was fixed in 97887cf.

You have to remove the downloaded script and download it again with the command in the README.md.

I look forward to hearing from you.
Best regards
Tim
