### ISSUE TITLE
homeassistant-supervised : Depends: docker-ce but it is not installable

### ISSUE THREAD

**Issue by AntoineProvost** [HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5#5]
Hello there,

Thanks for your clear and amazing tutorial ! (For a new user of python, it's great to have all these "check" steps to see if the previous one worked).

Unfortunately I'm stuck at the very end of the install when running the "apt install" :

```
apt install ./homeassistant-supervised.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'homeassistant-supervised' instead of './homeassistant-supervised.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 homeassistant-supervised : Depends: docker-ce but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Do you have an idea how I can resolve that ?

**Comment by HuckleberryLovesYou** [comment]
Thanks for your Response! 
Which way did you use to install Docker-ce? The problem might be that I had no way of testing the script in variant 1. That could mean something doesn't go right. The check-step only checks docker-ce and docker-cli. If you used variant 1 please try again using variant 2 after taking a look into the Troubleshooting Section, where the uninstall of the unfinished setup happens. Otherwise check if the os agent you installed is the right one.

**Comment by AntoineProvost** [comment]
I already used the variant 2 as the first one didn't work at first
It seems however that if I rewind steps, that I can't update the docker :

```
apt update && apt upgrade -y
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease        
Hit:3 http://archive.raspberrypi.com/debian bookworm InRelease                 
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease                  
Ign:5 https://download.docker.com/linux/ubuntu bookworm InRelease              
Err:6 https://download.docker.com/linux/ubuntu bookworm Release
  404  Not Found [IP: 2600:9000:218f:6e00:3:db06:4200:93a1 443]
Reading package lists... Done
E: The repository 'https://download.docker.com/linux/ubuntu bookworm Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by HuckleberryLovesYou** [comment]
Hey, you might want to try all of the following commands to correct the dependencies. But first of all, ensure that you have docker-ce install. To do that run the following command:
```
sudo apt install docker-ce --reinstall
#or
sudo apt install docker-ce
#if it's actually not installed
```
After that, run the following command:
```
apt -f install
```
After that, please retry.

PS:
A quick google brought up the following command, but I'm not sure at all what is does nor how it works:
```
dpkg --force-all --configure -a
```

**Comment by skutoroff** [comment]
With respect to installing homeassistant-supervised on Trixie...
I successfully used instructions from Gemini to remove the docker-cd dependency.

The install was successful, bur It looks like docker is not running.

How do I fix this one?

Here is the install script output:
--2025-11-24-------------------------
root@HASupervised13:~# apt install ./homeassistant-supervised2.deb -y
Note, selecting 'homeassistant-supervised' instead of './homeassistant-supervised2.deb'
Installing:
  homeassistant-supervised

Summary:
  Upgrading: 0, Installing: 1, Removing: 0, Not Upgrading: 0
  Download size: 0 B / 7,496 B
  Space needed: 0 B / 113 GB available

Get:1 /root/homeassistant-supervised2.deb homeassistant-supervised all 3.1.1 [7,496 B]
Preconfiguring packages ...                   
Selecting previously unselected package homeassistant-supervised.
(Reading database ... 120339 files and directories currently installed.)
Preparing to unpack .../homeassistant-supervised2.deb ...
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
[warn] ModemManager service is enabled. This might cause issue when using serial devices.
/var/lib/dpkg/tmp.ci/preinst: line 70: docker: command not found
Adding 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised'
Adding 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-
supervised'
Adding 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised'
Adding 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised'
Adding 'diversion of /etc/systemd/resolved.conf to /etc/systemd/resolved.conf.real by homeassistant-supervised'
Unpacking homeassistant-supervised (3.1.1) ...
Setting up homeassistant-supervised (3.1.1) ...
[info] Reload systemd
[info] Restarting NetworkManager
[info] Enable systemd-resolved
[info] Restarting systemd-resolved
[info] Set up systemd-journal-gatewayd socket file
[info] Enable systemd-journal-gatewayd
[info] Start nfs-utils.service
[info] Restarting docker service
Failed to restart docker.service: Unit docker.service not found.
dpkg: error processing package homeassistant-supervised (--configure):
 installed homeassistant-supervised package post-installation script subprocess returned error exit status 5
Errors were encountered while processing:
 homeassistant-supervised
Notice: Download is performed unsandboxed as root as file '/root/homeassistant-supervised2.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
Error: Sub-process /usr/bin/dpkg returned an error code (1)
root@HASupervised13:~#

**Comment by skutoroff** [comment]
I had Trixie running HA-supervised with PiHole and my enhanced infinitive.
Required some effort to get docker running.
Installed Docker per: https://linuxiac.com/how-to-install-docker-on-debian-13-trixie/
Fixed Docker-CE pre-dependency with:
Extract the .deb package: `dpkg-deb -x your-package-name.deb temp_directory`
Extract the control archive:  `dpkg-deb --control your-package-name.deb temp_directory/DEBIAN`
Edit the control file: Open temp_directory/DEBIAN/control using a text editor.
Locate the Depends line and remove docker-ce
Repackage the control archive:  `dpkg-deb --build temp_directory your-modified-package.deb`
Upon restart...
My Pi400 seemed unhappy, uptime showed very high loads .
HA supervised under Trixie was very unhappy, complained about the unsupported OS and my 32bit hardware (which it is not and the installed Trixie is 64bit).
Many errors after importing my HA configuration.
It did work.
Free memory under Trixie was higher than under Bookworm.
Overall, it was educational and pointless.
Back to my HA on Bookworm and come January I'll decide what do about the unsupported supervised HA.
If it doesn't look safe to continue with supervised, I'll probably run HAOS on a Pi4 or my naked Pi400 board.
Not worth wasting a Pi5 on it.
Or I'll drop HA completely.
--- 2025-12-03 ---
Still on Trixie.
Removed apparmor, ha-supervised, and the files in /root from the pre-depenency effort.
Installed HA Container
Works fine. Wasn't using he two add-ons I had installed anyway.
May see about removing OS-agent later.

> You can't always get what you want
> But if you try sometime you'll find
> You get what you need

Thanks all, It was quite a ride. Supervised will be missed and then forgotten.
