### ISSUE TITLE
AppArmor issues, Unhealthy system - Docker misconfigured & Unsupported system - Unsupported software

### ISSUE THREAD

**Issue by texplorer1** [HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5#6]
I got the above errors after I used The BangerTECH Utility to install its built-in Home Assistant version first. Then I saw this project, went on and followed your tutorials, and installed the HomeAssistant Supervised.

**Comment by HuckleberryLovesYou** [comment]
That's great to hear! Thank you! The BangerTECH Utility is going to install the Core Version of Homeassistant which doesn't come with addons. Am I correct in assuming that you have nothing further?

**Comment by texplorer1** [comment]
No. Sorry about the miscommunication. The errors are still there. What I am trying to say is I have both versions of HA installed. I don't know if this dual setup contribute to the errors I am getting.

**Comment by HuckleberryLovesYou** [comment]
Oh, now I got it!
Is it possible, that you are referring to issue #1 ?
Please take a look there and let me know if the issue persists.

**Comment by texplorer1** [comment]
Thanks so much. I learned that I need to remove 'apparmor=1 security=apparmor' from the config.txt and have it only in the cmdline.txt. Should I keep 'kernel=kernel8.img' in config.txt?
Also, when I tried to install addons, it prompts 'AddonManager.install' blocked from execution, system is not healthy - docker'

**Comment by HuckleberryLovesYou** [comment]
Great! If I'm going right, the needed configuration in cmdline.txt and config.txt changed since my last attempt. Since then, Homeassistant is now officially supported on Raspberry Pi 5. Would you like to create a PR, for a addition to the Troubleshooting Section at the bottom of the Readme? There Kernel8.img was needed back then, where while installing Homeassistant you had to choose the Pi 4 variant, which needed Kernel8.img. If installed with the Pi 5 variant, it might not be needed. Referring to the addon error: I actually never heard about it, but I could think of a reason for it. It might occur because of the usage of Portainer, which tries to take over control of containers. If your running Portainer, please thlry the fix mentioned in the Troubleshooting Section at the bottom of the Readmd.
